### ISSUE TITLE
Issue in billing

### ISSUE THREAD

**Issue by GarimaPhuyal** [Hemantbam/Restaurant_Management_System_api_main#1]
After the waiter notifies the cashier about the completion of an order, the total price of the food items is not showing up on the cashier's page.
![billinggwhg](https://user-images.githubusercontent.com/119827578/236719570-d97223ef-baa6-4239-b2c4-24737c8428ef.png)

**Comment by Hemantbam** [comment]
Hello Garima, The issue has been solved. The billing dashboard will now show the price for the orders.
![image](https://github.com/Hemantbam/Restaurant_Management_System_api_main/assets/107202719/eee8e431-b3df-4b60-af06-338d3aa6c0d8)
